app:
  title: "H15-Hub"
  description: "Hebewerk e.V. Makerspace Integration Hub"
  poll_interval_seconds: 5

devices:
  bambu:
    adapter: bambuddy
    url: http://makerspace:8000
    printers:
      - id: bambu-p1s-ams
        name: "Bambu P1S AMS"
      - id: bambu-p1p
        name: "Bambu P1P"

  homeassistant:
    adapter: homeassistant
    url: http://192.168.181.111/:8123
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzNTg5ZTBhMDY4ZjU0OTk5YjJlYzM4NTI5NTk0M2FjMiIsImlhdCI6MTc3MzA1MTA5OCwiZXhwIjoyMDg4NDExMDk4fQ.ACG88loH_-qyQ9xprj8xroIJiqPQrPQsBI62qU2luSs"
    entities:
      - entity_id: select.kombi_kuhlschrank_einschaltzustand
        name: Kühlschrank
        type: Schalter
      - entity_id: binary_sensor.werkstatt_besetzt
        name: Offene Werkstatt
        type: sensor

  labelprinter:
    adapter: labelprinter
    model: QL-500
    device: /dev/usb/lp0
    name: "Labeldrucker"

  laserprinter:
    adapter: laserprinter
    url: ipp://192.168.1.50/ipp/print
    name: "Büro Laserdrucker"

automations: []
